// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class AppConnectionGcp extends pulumi.CustomResource {
    /**
     * Get an existing AppConnectionGcp resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AppConnectionGcpState, opts?: pulumi.CustomResourceOptions): AppConnectionGcp {
        return new AppConnectionGcp(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/appConnectionGcp:AppConnectionGcp';

    /**
     * Returns true if the given object is an instance of AppConnectionGcp.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AppConnectionGcp {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AppConnectionGcp.__pulumiType;
    }

    /**
     * The credentials for the GCP App Connection
     */
    public readonly credentials!: pulumi.Output<outputs.AppConnectionGcpCredentials>;
    /**
     * The hash of the GCP App Connection credentials
     */
    public /*out*/ readonly credentialsHash!: pulumi.Output<string>;
    /**
     * An optional description for the GCP App Connection.
     */
    public readonly description!: pulumi.Output<string | undefined>;
    /**
     * The method used to authenticate with GCP. Possible values are: service-account-impersonation
     */
    public readonly method!: pulumi.Output<string>;
    /**
     * The name of the GCP App Connection to create. Must be slug-friendly
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a AppConnectionGcp resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AppConnectionGcpArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AppConnectionGcpArgs | AppConnectionGcpState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AppConnectionGcpState | undefined;
            resourceInputs["credentials"] = state ? state.credentials : undefined;
            resourceInputs["credentialsHash"] = state ? state.credentialsHash : undefined;
            resourceInputs["description"] = state ? state.description : undefined;
            resourceInputs["method"] = state ? state.method : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as AppConnectionGcpArgs | undefined;
            if ((!args || args.credentials === undefined) && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            if ((!args || args.method === undefined) && !opts.urn) {
                throw new Error("Missing required property 'method'");
            }
            resourceInputs["credentials"] = args ? args.credentials : undefined;
            resourceInputs["description"] = args ? args.description : undefined;
            resourceInputs["method"] = args ? args.method : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["credentialsHash"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AppConnectionGcp.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering AppConnectionGcp resources.
 */
export interface AppConnectionGcpState {
    /**
     * The credentials for the GCP App Connection
     */
    credentials?: pulumi.Input<inputs.AppConnectionGcpCredentials>;
    /**
     * The hash of the GCP App Connection credentials
     */
    credentialsHash?: pulumi.Input<string>;
    /**
     * An optional description for the GCP App Connection.
     */
    description?: pulumi.Input<string>;
    /**
     * The method used to authenticate with GCP. Possible values are: service-account-impersonation
     */
    method?: pulumi.Input<string>;
    /**
     * The name of the GCP App Connection to create. Must be slug-friendly
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AppConnectionGcp resource.
 */
export interface AppConnectionGcpArgs {
    /**
     * The credentials for the GCP App Connection
     */
    credentials: pulumi.Input<inputs.AppConnectionGcpCredentials>;
    /**
     * An optional description for the GCP App Connection.
     */
    description?: pulumi.Input<string>;
    /**
     * The method used to authenticate with GCP. Possible values are: service-account-impersonation
     */
    method: pulumi.Input<string>;
    /**
     * The name of the GCP App Connection to create. Must be slug-friendly
     */
    name?: pulumi.Input<string>;
}
