// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getProjects(args: GetProjectsArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("infisical:index/getProjects:getProjects", {
        "slug": args.slug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProjects.
 */
export interface GetProjectsArgs {
    slug: string;
}

/**
 * A collection of values returned by getProjects.
 */
export interface GetProjectsResult {
    readonly autoCapitalization: boolean;
    readonly createdAt: string;
    readonly environments: {[key: string]: outputs.GetProjectsEnvironments};
    readonly id: string;
    readonly name: string;
    readonly orgId: string;
    readonly slug: string;
    readonly updatedAt: string;
    readonly upgradeStatus: string;
    readonly version: number;
}
export function getProjectsOutput(args: GetProjectsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProjectsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("infisical:index/getProjects:getProjects", {
        "slug": args.slug,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getProjects.
 */
export interface GetProjectsOutputArgs {
    slug: pulumi.Input<string>;
}
