// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IdentityUniversalAuth extends pulumi.CustomResource {
    /**
     * Get an existing IdentityUniversalAuth resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityUniversalAuthState, opts?: pulumi.CustomResourceOptions): IdentityUniversalAuth {
        return new IdentityUniversalAuth(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityUniversalAuth:IdentityUniversalAuth';

    /**
     * Returns true if the given object is an instance of IdentityUniversalAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityUniversalAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityUniversalAuth.__pulumiType;
    }

    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenMaxTtl!: pulumi.Output<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    public readonly accessTokenNumUsesLimit!: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    public readonly accessTokenTrustedIps!: pulumi.Output<outputs.IdentityUniversalAuthAccessTokenTrustedIp[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenTtl!: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that the Client Secret can be used from together with the Client ID to get back an access
     * token. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    public readonly clientSecretTrustedIps!: pulumi.Output<outputs.IdentityUniversalAuthClientSecretTrustedIp[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    public readonly identityId!: pulumi.Output<string>;

    /**
     * Create a IdentityUniversalAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityUniversalAuthArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityUniversalAuthArgs | IdentityUniversalAuthState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityUniversalAuthState | undefined;
            resourceInputs["accessTokenMaxTtl"] = state ? state.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = state ? state.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = state ? state.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = state ? state.accessTokenTtl : undefined;
            resourceInputs["clientSecretTrustedIps"] = state ? state.clientSecretTrustedIps : undefined;
            resourceInputs["identityId"] = state ? state.identityId : undefined;
        } else {
            const args = argsOrState as IdentityUniversalAuthArgs | undefined;
            if ((!args || args.identityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            resourceInputs["accessTokenMaxTtl"] = args ? args.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = args ? args.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = args ? args.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = args ? args.accessTokenTtl : undefined;
            resourceInputs["clientSecretTrustedIps"] = args ? args.clientSecretTrustedIps : undefined;
            resourceInputs["identityId"] = args ? args.identityId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityUniversalAuth.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityUniversalAuth resources.
 */
export interface IdentityUniversalAuthState {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityUniversalAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that the Client Secret can be used from together with the Client ID to get back an access
     * token. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    clientSecretTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityUniversalAuthClientSecretTrustedIp>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IdentityUniversalAuth resource.
 */
export interface IdentityUniversalAuthArgs {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityUniversalAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that the Client Secret can be used from together with the Client ID to get back an access
     * token. You can use 0.0.0.0/0, to allow usage from any network address.
     */
    clientSecretTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityUniversalAuthClientSecretTrustedIp>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId: pulumi.Input<string>;
}
