// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IdentityAzureAuth extends pulumi.CustomResource {
    /**
     * Get an existing IdentityAzureAuth resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityAzureAuthState, opts?: pulumi.CustomResourceOptions): IdentityAzureAuth {
        return new IdentityAzureAuth(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityAzureAuth:IdentityAzureAuth';

    /**
     * Returns true if the given object is an instance of IdentityAzureAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityAzureAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityAzureAuth.__pulumiType;
    }

    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenMaxTtl!: pulumi.Output<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    public readonly accessTokenNumUsesLimit!: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    public readonly accessTokenTrustedIps!: pulumi.Output<outputs.IdentityAzureAuthAccessTokenTrustedIp[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenTtl!: pulumi.Output<number>;
    /**
     * List of Azure AD service principal IDs that are allowed to authenticate with Infisical
     */
    public readonly allowedServicePrincipalIds!: pulumi.Output<string[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    public readonly identityId!: pulumi.Output<string>;
    /**
     * The resource URL for the application registered in Azure AD. The value is expected to match the `aud` claim of the
     * access token JWT later used in the login operation against Infisical. See the
     * [resource](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http)
     * parameter for how the audience is set when requesting a JWT access token from the Azure Instance Metadata Service (IMDS)
     * endpoint. In most cases, this value should be `https://management.azure.com/` which is the default
     */
    public readonly resourceUrl!: pulumi.Output<string>;
    /**
     * The [tenant ID](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-find-tenant) for the Azure AD organization.
     */
    public readonly tenantId!: pulumi.Output<string>;

    /**
     * Create a IdentityAzureAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityAzureAuthArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityAzureAuthArgs | IdentityAzureAuthState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityAzureAuthState | undefined;
            resourceInputs["accessTokenMaxTtl"] = state ? state.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = state ? state.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = state ? state.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = state ? state.accessTokenTtl : undefined;
            resourceInputs["allowedServicePrincipalIds"] = state ? state.allowedServicePrincipalIds : undefined;
            resourceInputs["identityId"] = state ? state.identityId : undefined;
            resourceInputs["resourceUrl"] = state ? state.resourceUrl : undefined;
            resourceInputs["tenantId"] = state ? state.tenantId : undefined;
        } else {
            const args = argsOrState as IdentityAzureAuthArgs | undefined;
            if ((!args || args.identityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            if ((!args || args.tenantId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'tenantId'");
            }
            resourceInputs["accessTokenMaxTtl"] = args ? args.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = args ? args.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = args ? args.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = args ? args.accessTokenTtl : undefined;
            resourceInputs["allowedServicePrincipalIds"] = args ? args.allowedServicePrincipalIds : undefined;
            resourceInputs["identityId"] = args ? args.identityId : undefined;
            resourceInputs["resourceUrl"] = args ? args.resourceUrl : undefined;
            resourceInputs["tenantId"] = args ? args.tenantId : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityAzureAuth.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityAzureAuth resources.
 */
export interface IdentityAzureAuthState {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityAzureAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * List of Azure AD service principal IDs that are allowed to authenticate with Infisical
     */
    allowedServicePrincipalIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId?: pulumi.Input<string>;
    /**
     * The resource URL for the application registered in Azure AD. The value is expected to match the `aud` claim of the
     * access token JWT later used in the login operation against Infisical. See the
     * [resource](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http)
     * parameter for how the audience is set when requesting a JWT access token from the Azure Instance Metadata Service (IMDS)
     * endpoint. In most cases, this value should be `https://management.azure.com/` which is the default
     */
    resourceUrl?: pulumi.Input<string>;
    /**
     * The [tenant ID](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-find-tenant) for the Azure AD organization.
     */
    tenantId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IdentityAzureAuth resource.
 */
export interface IdentityAzureAuthArgs {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityAzureAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * List of Azure AD service principal IDs that are allowed to authenticate with Infisical
     */
    allowedServicePrincipalIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId: pulumi.Input<string>;
    /**
     * The resource URL for the application registered in Azure AD. The value is expected to match the `aud` claim of the
     * access token JWT later used in the login operation against Infisical. See the
     * [resource](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http)
     * parameter for how the audience is set when requesting a JWT access token from the Azure Instance Metadata Service (IMDS)
     * endpoint. In most cases, this value should be `https://management.azure.com/` which is the default
     */
    resourceUrl?: pulumi.Input<string>;
    /**
     * The [tenant ID](https://learn.microsoft.com/en-us/entra/fundamentals/how-to-find-tenant) for the Azure AD organization.
     */
    tenantId: pulumi.Input<string>;
}
