// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class IdentityGcpAuth extends pulumi.CustomResource {
    /**
     * Get an existing IdentityGcpAuth resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IdentityGcpAuthState, opts?: pulumi.CustomResourceOptions): IdentityGcpAuth {
        return new IdentityGcpAuth(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/identityGcpAuth:IdentityGcpAuth';

    /**
     * Returns true if the given object is an instance of IdentityGcpAuth.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IdentityGcpAuth {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IdentityGcpAuth.__pulumiType;
    }

    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenMaxTtl!: pulumi.Output<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    public readonly accessTokenNumUsesLimit!: pulumi.Output<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    public readonly accessTokenTrustedIps!: pulumi.Output<outputs.IdentityGcpAuthAccessTokenTrustedIp[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    public readonly accessTokenTtl!: pulumi.Output<number>;
    /**
     * List of trusted GCP projects that the GCE instance must belong to authenticate with Infisical. Note that this validation
     * property will only work for GCE instances
     */
    public readonly allowedProjects!: pulumi.Output<string[]>;
    /**
     * List of trusted service account emails corresponding to the GCE resource(s) allowed to authenticate with Infisical; this
     * could be something like `test@project.iam.gserviceaccount.com`, `12345-compute@developer.gserviceaccount.com`, etc.
     */
    public readonly allowedServiceAccountEmails!: pulumi.Output<string[]>;
    /**
     * List of trusted zones that the GCE instances must belong to authenticate with Infisical; this should be the
     * fully-qualified zone name in the format `<region>-<zone>`like `us-central1-a`, `us-west1-b`, etc. Note that this
     * validation property will only work for GCE instances.
     */
    public readonly allowedZones!: pulumi.Output<string[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    public readonly identityId!: pulumi.Output<string>;
    /**
     * The Type of GCP Auth Method to use: Options are gce, iam. Default:gce
     */
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a IdentityGcpAuth resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IdentityGcpAuthArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IdentityGcpAuthArgs | IdentityGcpAuthState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IdentityGcpAuthState | undefined;
            resourceInputs["accessTokenMaxTtl"] = state ? state.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = state ? state.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = state ? state.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = state ? state.accessTokenTtl : undefined;
            resourceInputs["allowedProjects"] = state ? state.allowedProjects : undefined;
            resourceInputs["allowedServiceAccountEmails"] = state ? state.allowedServiceAccountEmails : undefined;
            resourceInputs["allowedZones"] = state ? state.allowedZones : undefined;
            resourceInputs["identityId"] = state ? state.identityId : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as IdentityGcpAuthArgs | undefined;
            if ((!args || args.identityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            resourceInputs["accessTokenMaxTtl"] = args ? args.accessTokenMaxTtl : undefined;
            resourceInputs["accessTokenNumUsesLimit"] = args ? args.accessTokenNumUsesLimit : undefined;
            resourceInputs["accessTokenTrustedIps"] = args ? args.accessTokenTrustedIps : undefined;
            resourceInputs["accessTokenTtl"] = args ? args.accessTokenTtl : undefined;
            resourceInputs["allowedProjects"] = args ? args.allowedProjects : undefined;
            resourceInputs["allowedServiceAccountEmails"] = args ? args.allowedServiceAccountEmails : undefined;
            resourceInputs["allowedZones"] = args ? args.allowedZones : undefined;
            resourceInputs["identityId"] = args ? args.identityId : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IdentityGcpAuth.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering IdentityGcpAuth resources.
 */
export interface IdentityGcpAuthState {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityGcpAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * List of trusted GCP projects that the GCE instance must belong to authenticate with Infisical. Note that this validation
     * property will only work for GCE instances
     */
    allowedProjects?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of trusted service account emails corresponding to the GCE resource(s) allowed to authenticate with Infisical; this
     * could be something like `test@project.iam.gserviceaccount.com`, `12345-compute@developer.gserviceaccount.com`, etc.
     */
    allowedServiceAccountEmails?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of trusted zones that the GCE instances must belong to authenticate with Infisical; this should be the
     * fully-qualified zone name in the format `<region>-<zone>`like `us-central1-a`, `us-west1-b`, etc. Note that this
     * validation property will only work for GCE instances.
     */
    allowedZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId?: pulumi.Input<string>;
    /**
     * The Type of GCP Auth Method to use: Options are gce, iam. Default:gce
     */
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IdentityGcpAuth resource.
 */
export interface IdentityGcpAuthArgs {
    /**
     * The maximum lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenMaxTtl?: pulumi.Input<number>;
    /**
     * The maximum number of times that an access token can be used; a value of 0 implies infinite number of uses. Default:0
     */
    accessTokenNumUsesLimit?: pulumi.Input<number>;
    /**
     * A list of IPs or CIDR ranges that access tokens can be used from. You can use 0.0.0.0/0, to allow usage from any network
     * address..
     */
    accessTokenTrustedIps?: pulumi.Input<pulumi.Input<inputs.IdentityGcpAuthAccessTokenTrustedIp>[]>;
    /**
     * The lifetime for an access token in seconds. This value will be referenced at renewal time. Default: 2592000
     */
    accessTokenTtl?: pulumi.Input<number>;
    /**
     * List of trusted GCP projects that the GCE instance must belong to authenticate with Infisical. Note that this validation
     * property will only work for GCE instances
     */
    allowedProjects?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of trusted service account emails corresponding to the GCE resource(s) allowed to authenticate with Infisical; this
     * could be something like `test@project.iam.gserviceaccount.com`, `12345-compute@developer.gserviceaccount.com`, etc.
     */
    allowedServiceAccountEmails?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * List of trusted zones that the GCE instances must belong to authenticate with Infisical; this should be the
     * fully-qualified zone name in the format `<region>-<zone>`like `us-central1-a`, `us-west1-b`, etc. Note that this
     * validation property will only work for GCE instances.
     */
    allowedZones?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The ID of the identity to attach the configuration onto.
     */
    identityId: pulumi.Input<string>;
    /**
     * The Type of GCP Auth Method to use: Options are gce, iam. Default:gce
     */
    type?: pulumi.Input<string>;
}
