// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ProjectIdentity extends pulumi.CustomResource {
    /**
     * Get an existing ProjectIdentity resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectIdentityState, opts?: pulumi.CustomResourceOptions): ProjectIdentity {
        return new ProjectIdentity(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/projectIdentity:ProjectIdentity';

    /**
     * Returns true if the given object is an instance of ProjectIdentity.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectIdentity {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectIdentity.__pulumiType;
    }

    /**
     * The identity details of the project identity
     */
    public /*out*/ readonly identity!: pulumi.Output<outputs.ProjectIdentityIdentity>;
    /**
     * The id of the identity.
     */
    public readonly identityId!: pulumi.Output<string>;
    /**
     * The membership Id of the project identity
     */
    public /*out*/ readonly membershipId!: pulumi.Output<string>;
    /**
     * The id of the project
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * The roles assigned to the project identity
     */
    public readonly roles!: pulumi.Output<outputs.ProjectIdentityRole[]>;

    /**
     * Create a ProjectIdentity resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectIdentityArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectIdentityArgs | ProjectIdentityState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectIdentityState | undefined;
            resourceInputs["identity"] = state ? state.identity : undefined;
            resourceInputs["identityId"] = state ? state.identityId : undefined;
            resourceInputs["membershipId"] = state ? state.membershipId : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["roles"] = state ? state.roles : undefined;
        } else {
            const args = argsOrState as ProjectIdentityArgs | undefined;
            if ((!args || args.identityId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'identityId'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.roles === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roles'");
            }
            resourceInputs["identityId"] = args ? args.identityId : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["roles"] = args ? args.roles : undefined;
            resourceInputs["identity"] = undefined /*out*/;
            resourceInputs["membershipId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectIdentity.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProjectIdentity resources.
 */
export interface ProjectIdentityState {
    /**
     * The identity details of the project identity
     */
    identity?: pulumi.Input<inputs.ProjectIdentityIdentity>;
    /**
     * The id of the identity.
     */
    identityId?: pulumi.Input<string>;
    /**
     * The membership Id of the project identity
     */
    membershipId?: pulumi.Input<string>;
    /**
     * The id of the project
     */
    projectId?: pulumi.Input<string>;
    /**
     * The roles assigned to the project identity
     */
    roles?: pulumi.Input<pulumi.Input<inputs.ProjectIdentityRole>[]>;
}

/**
 * The set of arguments for constructing a ProjectIdentity resource.
 */
export interface ProjectIdentityArgs {
    /**
     * The id of the identity.
     */
    identityId: pulumi.Input<string>;
    /**
     * The id of the project
     */
    projectId: pulumi.Input<string>;
    /**
     * The roles assigned to the project identity
     */
    roles: pulumi.Input<pulumi.Input<inputs.ProjectIdentityRole>[]>;
}
