// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ProjectGroup extends pulumi.CustomResource {
    /**
     * Get an existing ProjectGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectGroupState, opts?: pulumi.CustomResourceOptions): ProjectGroup {
        return new ProjectGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/projectGroup:ProjectGroup';

    /**
     * Returns true if the given object is an instance of ProjectGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectGroup.__pulumiType;
    }

    /**
     * The id of the group.
     */
    public readonly groupId!: pulumi.Output<string>;
    /**
     * The name of the group.
     */
    public readonly groupName!: pulumi.Output<string | undefined>;
    /**
     * The membership Id of the project group
     */
    public /*out*/ readonly membershipId!: pulumi.Output<string>;
    /**
     * The id of the project.
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * The roles assigned to the project group
     */
    public readonly roles!: pulumi.Output<outputs.ProjectGroupRole[]>;

    /**
     * Create a ProjectGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectGroupArgs | ProjectGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectGroupState | undefined;
            resourceInputs["groupId"] = state ? state.groupId : undefined;
            resourceInputs["groupName"] = state ? state.groupName : undefined;
            resourceInputs["membershipId"] = state ? state.membershipId : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["roles"] = state ? state.roles : undefined;
        } else {
            const args = argsOrState as ProjectGroupArgs | undefined;
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.roles === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roles'");
            }
            resourceInputs["groupId"] = args ? args.groupId : undefined;
            resourceInputs["groupName"] = args ? args.groupName : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["roles"] = args ? args.roles : undefined;
            resourceInputs["membershipId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectGroup.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProjectGroup resources.
 */
export interface ProjectGroupState {
    /**
     * The id of the group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * The name of the group.
     */
    groupName?: pulumi.Input<string>;
    /**
     * The membership Id of the project group
     */
    membershipId?: pulumi.Input<string>;
    /**
     * The id of the project.
     */
    projectId?: pulumi.Input<string>;
    /**
     * The roles assigned to the project group
     */
    roles?: pulumi.Input<pulumi.Input<inputs.ProjectGroupRole>[]>;
}

/**
 * The set of arguments for constructing a ProjectGroup resource.
 */
export interface ProjectGroupArgs {
    /**
     * The id of the group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * The name of the group.
     */
    groupName?: pulumi.Input<string>;
    /**
     * The id of the project.
     */
    projectId: pulumi.Input<string>;
    /**
     * The roles assigned to the project group
     */
    roles: pulumi.Input<pulumi.Input<inputs.ProjectGroupRole>[]>;
}
