// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * The provider type for the infisical package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'infisical';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * (DEPRECATED, Use the `auth` attribute), Machine identity client ID. Used to fetch/modify secrets for a given project.
     */
    public readonly clientId!: pulumi.Output<string | undefined>;
    /**
     * (DEPRECATED, use `auth` attribute), Machine identity client secret. Used to fetch/modify secrets for a given project
     */
    public readonly clientSecret!: pulumi.Output<string | undefined>;
    /**
     * Used to point the client to fetch secrets from your self hosted instance of Infisical. If not host is provided,
     * https://app.infisical.com is the default host. This attribute can also be set using the `INFISICAL_HOST` environment
     * variable
     */
    public readonly host!: pulumi.Output<string | undefined>;
    /**
     * (DEPRECATED, Use machine identity auth), Used to fetch/modify secrets for a given project
     */
    public readonly serviceToken!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["auth"] = pulumi.output(args ? args.auth : undefined).apply(JSON.stringify);
            resourceInputs["clientId"] = args?.clientId ? pulumi.secret(args.clientId) : undefined;
            resourceInputs["clientSecret"] = args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined;
            resourceInputs["host"] = args ? args.host : undefined;
            resourceInputs["serviceToken"] = args?.serviceToken ? pulumi.secret(args.serviceToken) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientId", "clientSecret", "serviceToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The configuration values for authentication
     */
    auth?: pulumi.Input<inputs.ProviderAuth>;
    /**
     * (DEPRECATED, Use the `auth` attribute), Machine identity client ID. Used to fetch/modify secrets for a given project.
     */
    clientId?: pulumi.Input<string>;
    /**
     * (DEPRECATED, use `auth` attribute), Machine identity client secret. Used to fetch/modify secrets for a given project
     */
    clientSecret?: pulumi.Input<string>;
    /**
     * Used to point the client to fetch secrets from your self hosted instance of Infisical. If not host is provided,
     * https://app.infisical.com is the default host. This attribute can also be set using the `INFISICAL_HOST` environment
     * variable
     */
    host?: pulumi.Input<string>;
    /**
     * (DEPRECATED, Use machine identity auth), Used to fetch/modify secrets for a given project
     */
    serviceToken?: pulumi.Input<string>;
}
