// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SecretTag extends pulumi.CustomResource {
    /**
     * Get an existing SecretTag resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretTagState, opts?: pulumi.CustomResourceOptions): SecretTag {
        return new SecretTag(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/secretTag:SecretTag';

    /**
     * Returns true if the given object is an instance of SecretTag.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SecretTag {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SecretTag.__pulumiType;
    }

    /**
     * Color code for the tag.
     */
    public readonly color!: pulumi.Output<string>;
    /**
     * The name for the new tag
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The project id associated with the secret tag
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * The slug for the new tag
     */
    public readonly slug!: pulumi.Output<string>;

    /**
     * Create a SecretTag resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretTagArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretTagArgs | SecretTagState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretTagState | undefined;
            resourceInputs["color"] = state ? state.color : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["projectId"] = state ? state.projectId : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as SecretTagArgs | undefined;
            if ((!args || args.color === undefined) && !opts.urn) {
                throw new Error("Missing required property 'color'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.slug === undefined) && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["color"] = args ? args.color : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["slug"] = args ? args.slug : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SecretTag.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SecretTag resources.
 */
export interface SecretTagState {
    /**
     * Color code for the tag.
     */
    color?: pulumi.Input<string>;
    /**
     * The name for the new tag
     */
    name?: pulumi.Input<string>;
    /**
     * The project id associated with the secret tag
     */
    projectId?: pulumi.Input<string>;
    /**
     * The slug for the new tag
     */
    slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SecretTag resource.
 */
export interface SecretTagArgs {
    /**
     * Color code for the tag.
     */
    color: pulumi.Input<string>;
    /**
     * The name for the new tag
     */
    name?: pulumi.Input<string>;
    /**
     * The project id associated with the secret tag
     */
    projectId: pulumi.Input<string>;
    /**
     * The slug for the new tag
     */
    slug: pulumi.Input<string>;
}
