// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Secret extends pulumi.CustomResource {
    /**
     * Get an existing Secret resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SecretState, opts?: pulumi.CustomResourceOptions): Secret {
        return new Secret(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'infisical:index/secret:Secret';

    /**
     * Returns true if the given object is an instance of Secret.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Secret {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Secret.__pulumiType;
    }

    /**
     * The environment slug of the secret to modify/create
     */
    public readonly envSlug!: pulumi.Output<string>;
    /**
     * The path to the folder where the given secret resides
     */
    public readonly folderPath!: pulumi.Output<string>;
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * The name of the secret
     */
    public readonly name!: pulumi.Output<string>;
    public readonly secretReminder!: pulumi.Output<outputs.SecretSecretReminder | undefined>;
    /**
     * Tag ids to be attached for the secrets.
     */
    public readonly tagIds!: pulumi.Output<string[] | undefined>;
    /**
     * The value of the secret
     */
    public readonly value!: pulumi.Output<string>;
    /**
     * The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
     */
    public readonly workspaceId!: pulumi.Output<string>;

    /**
     * Create a Secret resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SecretArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SecretArgs | SecretState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SecretState | undefined;
            resourceInputs["envSlug"] = state ? state.envSlug : undefined;
            resourceInputs["folderPath"] = state ? state.folderPath : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["secretReminder"] = state ? state.secretReminder : undefined;
            resourceInputs["tagIds"] = state ? state.tagIds : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
            resourceInputs["workspaceId"] = state ? state.workspaceId : undefined;
        } else {
            const args = argsOrState as SecretArgs | undefined;
            if ((!args || args.envSlug === undefined) && !opts.urn) {
                throw new Error("Missing required property 'envSlug'");
            }
            if ((!args || args.folderPath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'folderPath'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["envSlug"] = args ? args.envSlug : undefined;
            resourceInputs["folderPath"] = args ? args.folderPath : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["secretReminder"] = args ? args.secretReminder : undefined;
            resourceInputs["tagIds"] = args ? args.tagIds : undefined;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
            resourceInputs["workspaceId"] = args ? args.workspaceId : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Secret.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Secret resources.
 */
export interface SecretState {
    /**
     * The environment slug of the secret to modify/create
     */
    envSlug?: pulumi.Input<string>;
    /**
     * The path to the folder where the given secret resides
     */
    folderPath?: pulumi.Input<string>;
    lastUpdated?: pulumi.Input<string>;
    /**
     * The name of the secret
     */
    name?: pulumi.Input<string>;
    secretReminder?: pulumi.Input<inputs.SecretSecretReminder>;
    /**
     * Tag ids to be attached for the secrets.
     */
    tagIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The value of the secret
     */
    value?: pulumi.Input<string>;
    /**
     * The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
     */
    workspaceId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Secret resource.
 */
export interface SecretArgs {
    /**
     * The environment slug of the secret to modify/create
     */
    envSlug: pulumi.Input<string>;
    /**
     * The path to the folder where the given secret resides
     */
    folderPath: pulumi.Input<string>;
    /**
     * The name of the secret
     */
    name?: pulumi.Input<string>;
    secretReminder?: pulumi.Input<inputs.SecretSecretReminder>;
    /**
     * Tag ids to be attached for the secrets.
     */
    tagIds?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The value of the secret
     */
    value: pulumi.Input<string>;
    /**
     * The Infisical project ID (Required for Machine Identity auth, and service tokens with multiple scopes)
     */
    workspaceId?: pulumi.Input<string>;
}
