// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("infisical");

/**
 * The configuration values for authentication
 */
export declare const auth: outputs.config.Auth | undefined;
Object.defineProperty(exports, "auth", {
    get() {
        return __config.getObject<outputs.config.Auth>("auth");
    },
    enumerable: true,
});

/**
 * (DEPRECATED, Use the `auth` attribute), Machine identity client ID. Used to fetch/modify secrets for a given project.
 */
export declare const clientId: string | undefined;
Object.defineProperty(exports, "clientId", {
    get() {
        return __config.get("clientId");
    },
    enumerable: true,
});

/**
 * (DEPRECATED, use `auth` attribute), Machine identity client secret. Used to fetch/modify secrets for a given project
 */
export declare const clientSecret: string | undefined;
Object.defineProperty(exports, "clientSecret", {
    get() {
        return __config.get("clientSecret");
    },
    enumerable: true,
});

/**
 * Used to point the client to fetch secrets from your self hosted instance of Infisical. If not host is provided,
 * https://app.infisical.com is the default host. This attribute can also be set using the `INFISICAL_HOST` environment
 * variable
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * (DEPRECATED, Use machine identity auth), Used to fetch/modify secrets for a given project
 */
export declare const serviceToken: string | undefined;
Object.defineProperty(exports, "serviceToken", {
    get() {
        return __config.get("serviceToken");
    },
    enumerable: true,
});

